### PR TITLE
Add lunacy and made the list awesome friendly

### PR DESCRIPTION
**Pull request by Jogai**
Added lunacy.

I used [Awesome-lint](https://github.com/sindresorhus/awesome-lint) to adjust the list a bit so the readme is ready to add it to the awesome list. To do that the repo still needs a contributing.md and awesome topics, among other requirements: https://github.com/sindresorhus/awesome/blob/main/pull_request_template.md#requirements-for-your-awesome-list

### CODE REVIEW

**Review by michaeldera — APPROVED** [review]
Looks great to me.

**Comment by michaeldera** [comment]
> Added lunacy.
> 
> I used [Awesome-lint](https://github.com/sindresorhus/awesome-lint) to adjust the list a bit so the readme is ready to add it to the awesome list. To do that the repo still needs a contributing.md and awesome topics, among other requirements: https://github.com/sindresorhus/awesome/blob/main/pull_request_template.md#requirements-for-your-awesome-list

You are right, there are a lot of changes that can be made here. The author of the project initially just did it as a list but is very open to contribution on it.

**Comment by michaeldera** [comment]
Thank you for your contribution.

**Comment by kudapara** [comment]
I have been away this weekend, thanks @Jogai for the awesome contribution and thank you @michaeldera for reviewing and merging this.

**Pull request merged**
